= Thorntail Insult Starter

IMPORTANT: This application requires Java 8 JDK or greater and Maven 3.3.x.

This application is a starter project for the Red Hat Summit Workshop, "Verily, ye be a knavish, tickle-brained, pantaloon: A hands-on microservices workshop"

This application contains a basic, "Hello, World!" application that we will customize during the workshop.

== Runing Locally

To run this booster on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ git clone git@github.com:jeremyrdavis/thorntail-insult-starter

$ cd thorntail-insult-starter

$ mvn thorntail:run
----

== Interacting with the application Locally

To interact with the starter application while it's running locally, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----


== Customizing the Booster
To update your booster:

. Stop your booster.
+
NOTE: To stop your running booster in a Linux or macOS terminal, use `CTRL+C`. In a Windows command prompt, you can use `CTRL + Break(pause)`.

. Make your change (e.g. edit `src/main/webapp/index.html`).
. Restart your booster.
. Verify the change took effect.


== Running the Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, link:http://launcher.fabric8.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u USER_NAME -p USER_PASSWORD

$ oc new-project MY_PROJECT_NAME

$ mvn clean fabric8:deploy -Popenshift
----

== More Information
You can learn more about this application and rest of the Thorntail runtime in the link:http://launcher.fabric8.io/docs/thorntail-runtime.html[Thorntail Runtime Guide].

NOTE: Run the set of integration tests included with this booster using `mvn clean verify -Popenshift,openshift-it`.
